# Reboots stateful CI agents.
# Is the CI acting strange? Try turning it off and on again.

trigger: none

name: 0.$(Date:yyyy).$(Date:MM).$(DayOfMonth).$(Rev:rr).0

stages:

- stage: reboot_agents
  displayName: Reboot CI Agents
  dependsOn: []
  jobs:
  - template: ./templates/reboot.yml
    parameters:
      pool: MsQuic
      agentName: INT-1
  - template: ./templates/reboot.yml
    parameters:
      pool: MsQuic
      agentName: INT-2
  - template: ./templates/reboot.yml
    parameters:
      pool: MsQuic
      agentName: INT-3
  - template: ./templates/reboot.yml
    parameters:
      pool: MsQuic
      agentName: INT-4
